//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usingwebservices.ConvertComputer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="ConvertComputer.ComputerUnitSoap")]
    public interface ComputerUnitSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ChangeComputerUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double ChangeComputerUnit(double ComputerValue, usingwebservices.ConvertComputer.Computers fromComputerUnit, usingwebservices.ConvertComputer.Computers toComputerUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ChangeComputerUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ChangeComputerUnitAsync(double ComputerValue, usingwebservices.ConvertComputer.Computers fromComputerUnit, usingwebservices.ConvertComputer.Computers toComputerUnit);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Computers {
        
        /// <remarks/>
        Bit,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Kilobyte,
        
        /// <remarks/>
        Megabyte,
        
        /// <remarks/>
        Gigabyte,
        
        /// <remarks/>
        Terabyte,
        
        /// <remarks/>
        Petabyte,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComputerUnitSoapChannel : usingwebservices.ConvertComputer.ComputerUnitSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComputerUnitSoapClient : System.ServiceModel.ClientBase<usingwebservices.ConvertComputer.ComputerUnitSoap>, usingwebservices.ConvertComputer.ComputerUnitSoap {
        
        public ComputerUnitSoapClient() {
        }
        
        public ComputerUnitSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComputerUnitSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputerUnitSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputerUnitSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ChangeComputerUnit(double ComputerValue, usingwebservices.ConvertComputer.Computers fromComputerUnit, usingwebservices.ConvertComputer.Computers toComputerUnit) {
            return base.Channel.ChangeComputerUnit(ComputerValue, fromComputerUnit, toComputerUnit);
        }
        
        public System.Threading.Tasks.Task<double> ChangeComputerUnitAsync(double ComputerValue, usingwebservices.ConvertComputer.Computers fromComputerUnit, usingwebservices.ConvertComputer.Computers toComputerUnit) {
            return base.Channel.ChangeComputerUnitAsync(ComputerValue, fromComputerUnit, toComputerUnit);
        }
    }
}
